Name: Hasnain khan

Roll No: 23102A0075

R-Programming Lab 3

***BASICS OP CALCULATIONS***

**R as a Calculator with Scalars and Data Vectors :**


Power operations, Integer and Modulo **divisions**

***R AS CALCULATOR***

In [ ]:
2^3 # POWER OPERATOR COMMAND

1

In [ ]:
2**3 #POWER OPERATOR COMMAND

8

In [ ]:
2^5

7

In [ ]:
2**0.5

1.4142135623730951

In [ ]:
2^-0.5

[1] 0.7071068

***POWER OPERATOR WITH SCALAR***

In [ ]:
c(2,3,5,7)^2

[1]  4  9 25 49

In [ ]:
c(2,3.5,7)^c(2,3)

Warning message in c(2, 3.5, 7)^c(2, 3):
“longer object length is not a multiple of shorter object length”

[1]  4.000 42.875 49.000

***POWER OPERATION WITH VECTOR***

In [ ]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

In [ ]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

***INTEGER DIVISON WITH SCALAR***

Integer Division: Division in which the fractional part
(remainder) is discarded

In [ ]:
2 %/% 2

[1] 1

In [ ]:
5 %/% 2

[1] 2

In [ ]:
7 %/% 3

[1] 2

In [ ]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

In [ ]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

***INTEGER DIVISION WITH DATA VECTOR***

In [ ]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

***MODULO DIVISION (X MOD Y) WITH SCALARS***

Modulo Division: modulo operation finds the remainder
after division of one number by another

In [ ]:
2 %% 2

[1] 0

In [ ]:
3 %% 2

[1] 1

In [ ]:
7 %% 3

[1] 1

In [ ]:
7 %% 4

[1] 3

In [ ]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

In [ ]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

In [ ]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

***BUILT IN FUNCTIONS AND ASSIGNMENTS***

***MAXIMUM***

In [ ]:
#operator:max

In [ ]:
max(1.2, 3.4, -7.8)

[1] 3.4

In [ ]:
max( c(1.2, 3.4, -7.4))

[1] 3.4

***MAXIMUM***

In [ ]:
min(1.2, 3.4, -7.8)

[1] -7.8

In [ ]:
min(c(1.2, 3.4, -7.8))

[1] -7.8

***ARITHMETIC MEAN***

In [ ]:
mean(2, 3, 4)

[1] 2

In [ ]:
mean(c(2, 3, 4))

[1] 3

***OTHER FUNCTIONS***

In [ ]:
abs(-4) #abs finds out absolute value

[1] 4

In [ ]:
abs(c(-1,-2,-3,4,5))

[1] 1 2 3 4 5

In [ ]:
sqrt(4) #sqrt finds square root of values

[1] 2

In [ ]:
sqrt(c(4,9,16,25))

[1] 2 3 4 5

In [ ]:
sum(c(2,3,5,7)) #sum finds sum of all values

[1] 17

In [ ]:
prod(c(2,3,5,7)) #prod finds out the product of all values

[1] 210

In [ ]:
round(1.23) #round finds out the round off values

[1] 1

In [ ]:
round(1.83)

[1] 2

In [ ]:
log(10) #log finds out the log(ln) values

[1] 2.302585

In [ ]:
log(exp(1))

[1] 1

In [ ]:
log(c(10, 100, 1000))

[1] 2.302585 4.605170 6.907755

In [ ]:
log10(10) #log(10) finds the log (with base 10) values

[1] 1

In [ ]:
log10(100)

[1] 2

In [ ]:
log10(1000)

[1] 3

In [ ]:
log10(c(10, 100, 1000))

[1] 1 2 3

***ASSIGMENT***

It can be use to save values in a variables

In [ ]:
x1 = c(1,2,3,4)
x1

[1] 1 2 3 4

In [ ]:
x2=x1^2
x2

[1]  1  4  9 16

Calculations with scalar, data vector and builnt in functions also work

In [ ]:
c(1,2,3,4) + sum(c(1,2,3,4))

[1] 11 12 13 14

In [ ]:
abs(c(1,2,3,4)) -sum(c(1,2,3,4))*prod(c(1,2,3,4))

[1] -239 -238 -237 -236

***MATRICES***

In R, a 4 × 2‐matrix X can be created with a following command:

In [ ]:
 X= matrix( nrow=4, ncol=2,
data=c(1,2,3,4,5,6,7,8) )

In [ ]:
X

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
#nrow defines row number
#ncol defines column number
#data assignes specified value

#--of the matrix--

***ACCESSING ANY ELEMENT OF A MATRIX***

In [ ]:
x <- matrix(c(1,2,3,4,5,6,7,8), nrow = 4, ncol = 2)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

***ENTERING DATA COLUMN WISE IN A MATRIX***

In [ ]:


x <- matrix(
  data = c(1,2,3,4,5,6,7,8),
  nrow = 4,
  ncol = 2
)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

***PROPETIES OF A MATRIX***

In [ ]:
dim(x) #let us now the dimension of the matrix

[1] 4 2

In [ ]:
nrow(x) #let us the no of rows

[1] 4

In [ ]:
ncol(x) #let us know the no of columns

[1] 2

In [ ]:
mode(x) # Informs the type or storage mode of an object, e.g., numerical, logical, etc

[1] "numeric"

In [ ]:
attributes(x) #informs the dimension of the matrix

$dim
[1] 4 2

***HELP ON THE OBJECT "MATRIX"***

In [ ]:
help("MATRIX")

***--THANKYOU--***