Name: Hasnain khan

Roll No: 23102A0075

R-Programming Lab 4

***Basics of Calculations***

**Matrix Operations – Row, Column & Other Operations**

***Matrix Operations***

**Renaming the row and column names**

In [1]:
x = matrix( nrow=4, ncol=3, data= c(1:12) )

In [2]:
 x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

In [3]:
rownames(x) #Renames the row names

NULL

In [4]:
colnames(x) #renames thr column names

NULL

In [6]:
 rownames(x) = c("r1", "r2", "r3", "r4")

***Renaming the row and column name***

In [7]:
x

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

In [8]:
colnames(x) = c("c1", "c2", "c3")

In [9]:
x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

***Assigning a specified number to all matrix elements:***

In [10]:
x = matrix( nrow=4, ncol=2, data=2 )

In [11]:
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

 ***Diagonal matrix***

Construction of a diagonal matrix, here the identity matrix of a
dimension 3:

In [12]:
d = diag(1, nrow=3, ncol=3)

In [13]:
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

Construction of a diagonal matrix with all numbers as 5 of a
dimension 3:

In [14]:
d = diag(5, nrow=3, ncol=3)

In [15]:
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

Transpose

Transpose of a matrix X:   X’

In [16]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T )

In [17]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

Transpose of a matrix X:   X’

In [18]:
xt = t(x)

In [19]:
xt

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

 Row and column sums

***Finding the row and column sums***

In [21]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

In [22]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

rowSums(x) #Finds the sum of numbers in rows

colSums(x) Finds the sum of numbers in columns

 ***Row and column means***

In [23]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [24]:
rowSums(x)

[1]  6  8 10 12

In [25]:
colSums(x)

[1] 10 26

***Finding the row and column mean***

In [26]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))

In [27]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [28]:
rowMeans(x) #Finds the means of rows

[1] 3 4 5 6

In [29]:
colMeans(x) #Finds the means of columns

[1] 2.5 6.5

In [30]:
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [31]:
rowMeans(x)

[1] 3 4 5 6

In [32]:
colMeans(x)

[1] 2.5 6.5

***Access and Mathematical Operations***

***Access to rows, columns or submatrices***

In [33]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)

In [34]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [35]:
x[3,]

[1] 7 8 9

In [36]:
x[,2]

[1]  2  5  8 11 14

In [37]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

In [38]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

In [39]:
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

Look at the outcome

[1] 2 5 8 11 14

Not possible to know if It is a row or a column.

***Addition of a matrix with a constant***

***Every element is added with the scalar***

In [40]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [41]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

***Subtraction of a matrix with a constant***

***Every element is subtracted by the scalar***

In [42]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [43]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

***Multiplication of a matrix with a constan***t

Every element is multiplied by the scalar

In [44]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [45]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

***Division of a matrix with a constant***

***Every element is divided by the scalar***

In [46]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [47]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

***Addition and subtraction of matrices***

Addition and subtraction of matrices (of same dimensions) can be
executed with the usual operators  +  and   -

In [48]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)

In [49]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [50]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

In [51]:
x+y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

In [52]:
x-y

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

In [53]:
4*x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [54]:
x+4*x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [55]:
4*x-x

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

***Multiplication of matrices***

Multiplication of matrices can be executed with the operator %*%

In [56]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

In [57]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [58]:
y

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [59]:
x%*%y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [60]:
y%*%x

     [,1] [,2]
[1,] 210  260
[2,] 274  340

Another example: Consider the multiplication of
X’ and X

In [61]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [62]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [63]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [65]:
t(x) %*% x

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [66]:
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

***Cross Product of a matrix X, X’X, with crossprod()***

In [68]:
 x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)

In [69]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [70]:
t(x)

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [71]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [72]:
#Note: Command crossprod()executes the multiplication faster than the conventional method with t(x)%*%x

Concatenating matrices

Concatenating matrices row wise: rbind(x, y)

Concatenating matrices column wise: cbind(x, y)

In [73]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)

In [74]:
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)

In [75]:
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

In [76]:
y

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

In [77]:
rbind(x,y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [78]:
cbind(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

***Inverse of matrix***

In [ ]:
#solve() finds the inverse of a positive definite matrix

In [80]:
y = matrix( nrow = 2, ncol = 2, byrow = T,
data = c(84,100,100,120))

In [81]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [82]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

***Eigen values and eigen vectors of matrix***

In [83]:
#eigen() finds the eigen values and eigen vectors of a positive  definite matrix

In [84]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data
= c(84,100,100,120))

In [85]:
y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [86]:
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

***Logical Operators***

***Logical Operators and Comparisons***

***Use of | and ||***

In [91]:
x=8
(x < 10) || (x < 2)

[1] TRUE

In [92]:
x=18
(x < 10) || (x < 2)

[1] FALSE

In [93]:
x = c(8,18)
x = c(8,18)

In [94]:
#| Operates only on the first element and not on remaining elements.

In [96]:
(x < 10) | (x < 2)

[1]  TRUE FALSE

In [ ]:
#| Operates on all the elements.

***Use of & and &&***

In [97]:
x=5
 (x < 10) && (x > 2)

[1] TRUE

In [98]:
x = 15
 (x < 10) && (x > 2)

[1] FALSE

In [102]:
x <- c(8, 18)

(x < 10) & (x > 2)

[1]  TRUE FALSE

In [103]:
x = 1:6 ## Generates x=1,2,3,4,5,6

In [105]:
(x > 2) & (x < 5) ## Checks whether the values are greater  than 2 and less than 5

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [107]:
x[(x > 2) & (x < 5)] # Finds which values  are greater than 2 and smaller than 5

[1] 3 4

In [108]:
x = 1:6

In [109]:
 (x > 2) | (x < 5) ## Checks whether the values are greater than 2 or less than 5

[1] TRUE TRUE TRUE TRUE TRUE TRUE

In [110]:
x[(x > 2) | (x < 5)] ## Finds which values are greater than 2 or smaller than 5

[1] 1 2 3 4 5 6

Example of The longer form evaluates left to right
examining only the first element of each vector

In [112]:
x = 1:6

In [114]:
(x > 2) & (x < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

R***elational and Logical Operators***

In [115]:
x = TRUE

In [116]:
y = FALSE

In [117]:
x & y # x AND y

[1] FALSE

In [118]:
x | y # x OR y

[1] TRUE

In [119]:
!x #negation of x

[1] FALSE

In [120]:
x = 5

In [121]:
Logical1 = (x > 2)

In [122]:
Logical1

[1] TRUE

In [123]:
is.logical(Logical1)

[1] TRUE

In [124]:
 Logical2 = (x < 10)
Logical2

[1] TRUE

In [125]:
is.logical(Logical2)

[1] TRUE

In [126]:
Logical3 = (x != 5)
 Logical3

[1] FALSE

In [127]:
 is.logical(Logical3)

[1] TRUE

In [128]:
x = 5

In [129]:
Logical4 = (2*x > 11)
Logical4

[1] FALSE

In [130]:
is.logical(Logical4)

[1] TRUE

In [131]:
Logical5 = (3*x <20)

In [132]:
 Logical5

[1] TRUE

In [133]:
is.logical(Logical5)

[1] TRUE

In [134]:
8 > 7
7>5
7>7
7>=7
8<8
8<=8
8!=9
9!=9
7==7
7==8
x=TRUE
!x

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

In [135]:
x = c(1, 2, 3)
 y = c(4, 5, 6)

In [136]:
 x > y # Compares 1 > 4, 2 > 5, 3 > 6

[1] FALSE FALSE FALSE

In [137]:
x < y # Compares 1 < 4, 2 < 5, 3 < 6

[1] TRUE TRUE TRUE

In [138]:
 x != y # Compares 1 ≠ 4, 2 ≠ 5, 3 ≠ 6

[1] TRUE TRUE TRUE

In [139]:
x == y # Compares 1 = 4, 2 = 5, 3 = 6

[1] FALSE FALSE FALSE

In [141]:
isTRUE(8 < 6)
isTRUE(8 > 6)
isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE